### ISSUE TITLE
Irritating NoClassDefFoundError

### ISSUE THREAD

**Issue by gschnepp** [javadelight/delight-rhino-sandbox#2]
Hi there,

coming from Proxy-vole, a project that uses delight-rhino-sandbox since version 1.0.4, I'm getting this exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.mozilla.javascript.VMBridge
        at org.mozilla.javascript.Context.exit(Context.java:434)
        at delight.rhinosandox.internal.RhinoSandboxImpl.assertContextFactory(RhinoSandboxImpl.java:68)
        at delight.rhinosandox.internal.RhinoSandboxImpl.evalWithGlobalScope(RhinoSandboxImpl.java:91)
        at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.setupEngine(JavaxPacScriptParser.java:80)
        at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.<init>(JavaxPacScriptParser.java:40)
```

But what's the reason? Package includes file VMBridge.class, so a NoClassDefFound exception is not clear to me.

BTW: There's an update available for Mozilla Rhino from 1.7.7 (used by rhino-sandbox 0.0.6) to 1.7.7.2.

Any help is appreciated.

Regards
Guido

**Comment by mxro** [comment]
Hi Guido,

Thank you for reporting the issue. Unfortunately I am travelling at the moment but I will have a look at the issue once I am back - that will be the first week of December. Sorry for the delay!

**Comment by mxro** [comment]
Hi Guido,

I had a quick look at your issue but unfortunately I couldn't quite figure out what is going on.

I've built the project on [travis-ci](https://travis-ci.org/javadelight/delight-rhino-sandbox) and all the tests seem to be running fine there.

I've released a fresh new version to Maven Central, maybe you could try it with that one?

```
<dependency>
    <groupId>org.javadelight</groupId>
    <artifactId>delight-rhino-sandbox</artifactId>
    <version>0.0.7</version>
</dependency>
```

Otherwise it seems that updating to 1.7.7.2 causes some compilation errors - so I will need to look into this in a bit more detail at a later stage.

What I found quite strange about the error that you get is that it only seems to be triggered when calling `Context.exit()`. I would think that the VMBridge class would have to be initialized before that - but maybe I am wrong!

I hope it will work with the new released version!

**Comment by gschnepp** [comment]
Max,

I can build a new version of my software with intermediate Proxy-vole library, that's all unfortunately. And I will update my issue there to mention your new release. Problem raised on customer side having problems to detect a proxy. So I'm not able to reproduce it directly.

Many thanks for your try anyway!

Regards
Guido

**Comment by gschnepp** [comment]
For your reference: https://github.com/MarkusBernhardt/proxy-vole/issues/33

**Comment by mxro** [comment]
Hi Guido,

Okay! Hope it gets solved!

Max

**Comment by gschnepp** [comment]
Max,

I've had another issue with same exception and DelightRhinoSandbox recently, again at customer site with no further option for debugging. Looking at the code of org.mozilla.javascript.Context.exit(Context.java:434), the problem seems to have to do with an uninitialized VMBridge.class object beforehand. Since you're calling this static function in RhinoSandboxImpl.assertContextFactory(RhinoSandboxImpl.java:68) in a finally {} block, may it be that this Context object never has been initialized before?

Anyway: The problem must have to do with invalid or unexpected JavaScript, since Proxy-Vole is trying to parse a PAC script ( https://de.wikipedia.org/wiki/Proxy_Auto-Config ) here, which is a specialized JavaScript subroutine. And this also meets the finding, that only a few customers of mine have this problem (those who have misconfigured their proxy auto configuration scripts - or have one in action in general).

I will try to get one of these PAC scripts from my customers, but it may be they're not willing to share.

Regards
Guido

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.mozilla.javascript.VMBridge
        at org.mozilla.javascript.Context.exit(Context.java:434)
        at delight.rhinosandox.internal.RhinoSandboxImpl.assertContextFactory(RhinoSandboxImpl.java:68)
        at delight.rhinosandox.internal.RhinoSandboxImpl.evalWithGlobalScope(RhinoSandboxImpl.java:91)
        at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.setupEngine(JavaxPacScriptParser.java:80)
        at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.<init>(JavaxPacScriptParser.java:40)
        at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.selectEngine(PacProxySelector.java:76)
        at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.<init>(PacProxySelector.java:41)
        at com.github.markusbernhardt.proxy.util.ProxyUtil.buildPacSelectorForUrl(ProxyUtil.java:90)
        at com.github.markusbernhardt.proxy.search.browser.ie.IEProxySearchStrategy.createPacSelector(IEProxySearchStrategy.java:114)
        at com.github.markusbernhardt.proxy.search.browser.ie.IEProxySearchStrategy.getProxySelector(IEProxySearchStrategy.java:40)
        at com.github.markusbernhardt.proxy.ProxySearch.getProxySelector(ProxySearch.java:216)
        at de.credo.afplookup.license.RegistrationProperties.activateProperties(RegistrationProperties.java:132)
        at de.credo.afplookup.license.Registration.<clinit>(Registration.java:80)

```

**Comment by mxro** [comment]
Hi Guido! Thank you for the update on the case! It's good to know more about what might be causing this.

I don't think it is possible that the Context object is not initialized at that point. It looks to me that for the Context.exit() routine the Context object maybe uses an dependency which before has not been used? 

Hope that looking at the script might bring some further insight!

**Comment by gschnepp** [comment]
Hi Max,

having a deeper look into the code of proxy-vole, it cannot have to do invalid PAC scripts, unfortunately. They all are provided unchanged for a long time by the library itself, in this case. (Problem raises in library initialization far before reading the custom scripts.) So there must be another reason for this problem.

I've had a look into your code then and - folling the path - into code of org.mozilla.javascript.VMBridge. It turns out that this class is created by a private static constructor "makeInstance()" trying to create different JDK-dependend versions of itself, so to say. It **can be**, that _**no**_ VMBridge instance can be created in this case, isn't it?

It successfully creates an instance of `org.mozilla.javascript.jdk15.VMBridge_jdk15` on my machine in every case, and so I'm helpless actually. But what I've found is, that there's a newer version of org.mozilla.rhino is available actually: You're using Rhino-1.7.7 from 2015 while **Rhino-1.7.7.2** is available since 2017. And: Upcoming release Rhino-1.7.8 for Java-8 and later is announced already, too.

Do you plan to update your dependencies regularly?

Guido

**Comment by mxro** [comment]
Hi Guido,

Thank you for the notification about the new Rhino version. So you are saying the issues might be caused by a bug in Rhino and that using the updated version might fix it? 

I bumped the Rhino version and released a new version of this library (0.0.8) on Maven central. Hope this helps!

Max

**Comment by gschnepp** [comment]
Closing because problem had to do with illegally stripped down fat JAR (maven-shade-plugin "minimizeJar" has removed necessary dynamic classes from Rhino library, too). My fault, more or less! :-(

**Comment by mxro** [comment]
Thank you for checking it and coming back to close the issue! If there is anything else, please let me know!
